name: Fly.io Deploy

inputs:
  app-name:
    description: 'Application name'
    required: true
  fly-api-token:
    description: 'API Token for Fly.io'
    required: true
  image-tag:
    description: 'The locally tagged docker image to push to Fly.io'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Login to Fly
      id: login-fly
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Push image to Fly
      id: push-image
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
        APP_NAME: ${{ inputs.app-name }}
        IMAGE_TAG: ${{ inputs.image-tag }}
      run: |
        flyctl auth docker
        docker build -t registry.fly.io/$APP_NAME:$IMAGE_TAG .
        docker push registry.fly.io/$APP_NAME:$IMAGE_TAG

    - name: Replace APP_NAME in task definition file
      id: replace-app-name
      shell: bash
      run: |
        sed -i 's/<APP_NAME>/${{ inputs.app-name }}/g' fly.toml

    - name: Deploy to Fly.io
      id: deploy
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-api-token }}
      run: |
        flyctl deploy --image registry.fly.io/${{ inputs.app-name }}:${{ inputs.image-tag }}
